
services:
  # node-app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./app:/usr/src/app
  #   command: npm run start
  node-app-cronback:
    build: .
    volumes:
      - ./app:/usr/src/app