name: Auto Increment Tag

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # нужно, чтобы пушить теги

jobs:
  autotag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # нужно, чтобы видеть все теги

      - name: Get latest tag
        id: get_tag
        run: |
          latest=$(git tag --sort=-v:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 1 || echo "v0.0.0")
          echo "latest=$latest" >> $GITHUB_OUTPUT
          echo "Latest tag: $latest"

      - name: Calculate next tag (major/minor/patch)
        id: next_tag
        run: |
          latest="${{ steps.get_tag.outputs.latest }}"
          IFS='.' read -r major minor patch <<<"${latest#v}"

          msg=$(git log -1 --pretty=%B | tr -d '\n')
          echo "Last commit message: $msg"

          if [[ "$msg" == *"[major]"* ]]; then
            major=$((major + 1))
            minor=0
            patch=0
            bump="major"
          elif [[ "$msg" == *"[minor]"* ]]; then
            minor=$((minor + 1))
            patch=0
            bump="minor"
          else
            patch=$((patch + 1))
            bump="patch"
          fi

          next="v$major.$minor.$patch"
          echo "next=$next" >> $GITHUB_OUTPUT
          echo "Bump type: $bump → Next tag: $next"

      - name: Create and push tag
        env:
          TAG: ${{ steps.next_tag.outputs.next }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$TAG"
          git push origin "$TAG"

      - name: Notify
        run: |
          echo "✅ Created and pushed new tag: ${{ steps.next_tag.outputs.next }}"