name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write      # нужно для ghcr
      id-token: write      # на будущее для подписей/provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          # имя образа: ghcr.io/OWNER/REPO
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha
            # дополнительно latest для main:
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Get commit and tag
        id: vars
        run: |
          echo "commit=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "tag=$(git describe --tags --always)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile               
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Notify Telegram
        if: success()
        run: |
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -H "Content-Type: application/json" \
            -d '{
              "chat_id": "'"${{ secrets.TG_CHAT_ID }}"'",
              "parse_mode": "Markdown",
              "text": "✅ *Docker образы собраны и опубликованы, НАДО ДЕПЛОИТЬ!*\n\n📦 Образы:\n- `ghcr.io/${{ github.repository }}t`\n-\n🧑 Коммит: `${{ steps.vars.outputs.commit }}`\n🏷️ Тег: `${{ steps.vars.outputs.tag }}`",
              "reply_markup": {
                "inline_keyboard": [[
                  {
                    "text": "🔍 Открыть GitHub Actions",
                    "url": "'"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"'"
                  }
                ]]
              }
            }'

      - name: Notify Telegram on failure
        if: failure()
        run: |
          LOG_FPM=$(tail -n 30 fpm_build.log | sed 's/$/%0A/' | tr -d '\n')
          LOG_NGINX=$(tail -n 30 nginx_build.log | sed 's/$/%0A/' | tr -d '\n')
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TG_BOT_TOKEN }}/sendMessage \
            -H "Content-Type: application/json" \
            -d '{
              "chat_id": "'"${{ secrets.TG_CHAT_ID }}"'",
              "parse_mode": "Markdown",
              "text": "❌ *Ошибка в GitHub Actions Workflow!*\n\n🧑 Автор: ${{ github.actor }}\n📝 Commit: `${{ github.sha }}`",
              "reply_markup": {
                "inline_keyboard": [[
                  {
                    "text": "📄 Открыть лог",
                    "url": "'"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"'"
                  }
                ]]
              }
            }'